### ISSUE TITLE
Application title not always fully visible

### ISSUE THREAD

**Issue by sankasan** [linuxappstore/linuxappstore-frontend#27]
Application title is cut off and no hover information so for users this is very confusing on which application they have to chose. An image says is better than words so see image attached.

![image](https://user-images.githubusercontent.com/2207658/57354157-163c4a00-716b-11e9-8c19-a238c5ec5a59.png)

**Comment by sankasan** [comment]
In addition, as a user I expect to select the appliction first, the distribution format later. Perhaps merge them into a single item and install in the details screen?

**Comment by chadalen** [comment]
This is fixed in version 0.3.2

**Comment by sankasan** [comment]
I'm not sure why you think this is now fixed. Below a screenshot of version 0.3.2 which still doesn't show longer titles.

![image](https://user-images.githubusercontent.com/2207658/57689444-d3351780-763f-11e9-87a3-934371667615.png)

**Comment by chadalen** [comment]
@sankasan Sorry the issue I fixed was a separate issue. The "App Store" text from being cut off on window resize. My bad

**Comment by chadalen** [comment]
@sankasan Can you try this now?

**Comment by sankasan** [comment]
Looks great now thanks! 

Now I need to figure out what the differences are betwen the Visual Studio Code versions actually are (insiders, OSS, normal) and the variants with the same name that are apparently allowed even per distribution method (vscode vs snapcrafters for the "Visual Studio Code" application).

It is still quite confusing which version to grab from the store.

**Comment by chadalen** [comment]
@sankasan I use the snap [https://snapcraft.io/code](https://snapcraft.io/code).

In Flatpak's visual studio code the terminal doesn't work

Snapcraft Insiders is the development build (has the latest version but unstable because it's changing everyday)

[https://snapcraft.io/vscode](https://snapcraft.io/vscode) Was the community maintained visual studio code whereas [https://snapcraft.io/code](https://snapcraft.io/code) is the official snap from microsoft
